"""‘重新创建数据表’

Revision ID: 22aede183f8f
Revises: 904575f2f97f
Create Date: 2021-01-30 19:15:49.812947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22aede183f8f'
down_revision = '904575f2f97f'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False, comment='用例ID'),
    sa.Column('SERIAL_NO', sa.String(length=128), nullable=False, comment='用例编号'),
    sa.Column('LEVEL', sa.String(length=1), nullable=False),
    sa.Column('DESCRIPTION', sa.String(length=32), nullable=False),
    sa.Column('REQUEST_METHOD', sa.Enum('GET', 'POST', 'PUT', 'DELETE', 'PATCH', 'HEAD', 'OPTIONS'), nullable=False),
    sa.Column('REQUEST_HEADERS', sa.JSON(), nullable=True),
    sa.Column('REQUEST_BODY', sa.JSON(), nullable=True),
    sa.Column('CREATE_TIME', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('UPDATE_TIME', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('DELETE_FLAG', sa.Boolean(), nullable=True, comment='删除标志'),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index(op.f('ix_case_SERIAL_NO'), 'case', ['SERIAL_NO'], unique=False)
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_case_SERIAL_NO'), table_name='case')
    op.drop_table('case')
    # ### end Alembic commands ###


def upgrade_extra():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_extra():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

