"""empty message

Revision ID: 904575f2f97f
Revises: d45e513b7836
Create Date: 2021-01-30 19:12:26.328124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '904575f2f97f'
down_revision = 'd45e513b7836'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case', sa.Column('DESCRIPTION', sa.String(length=32), nullable=False))
    op.add_column('case', sa.Column('LEVEL', sa.String(length=1), nullable=False))
    op.add_column('case', sa.Column('REQUEST_BODY', sa.JSON(), nullable=True))
    op.add_column('case', sa.Column('REQUEST_HEADERS', sa.JSON(), nullable=True))
    op.add_column('case', sa.Column('REQUEST_METHOD', sa.Enum('GET', 'POST', 'PUT', 'DELETE', 'PATCH', 'HEAD', 'OPTIONS'), nullable=False))
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('case', 'REQUEST_METHOD')
    op.drop_column('case', 'REQUEST_HEADERS')
    op.drop_column('case', 'REQUEST_BODY')
    op.drop_column('case', 'LEVEL')
    op.drop_column('case', 'DESCRIPTION')
    # ### end Alembic commands ###


def upgrade_extra():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_extra():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

