"""更新case模型

Revision ID: a192b31f65b5
Revises: 22aede183f8f
Create Date: 2021-01-31 10:59:20.544113

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a192b31f65b5'
down_revision = '22aede183f8f'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('case', 'DESCRIPTION',
               existing_type=mysql.VARCHAR(collation='utf8mb4_bin', length=32),
               comment='用例描述',
               existing_nullable=False)
    op.alter_column('case', 'LEVEL',
               existing_type=mysql.VARCHAR(collation='utf8mb4_bin', length=1),
               comment='用例等级',
               existing_nullable=False)
    op.alter_column('case', 'REQUEST_BODY',
               existing_type=mysql.JSON(),
               comment='请求体',
               existing_nullable=True)
    op.alter_column('case', 'REQUEST_HEADERS',
               existing_type=mysql.JSON(),
               comment='请求头',
               existing_nullable=True)
    op.alter_column('case', 'REQUEST_METHOD',
               existing_type=mysql.ENUM('GET', 'POST', 'PUT', 'DELETE', 'PATCH', 'HEAD', 'OPTIONS', collation='utf8mb4_bin'),
               comment='请求方法',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('case', 'REQUEST_METHOD',
               existing_type=mysql.ENUM('GET', 'POST', 'PUT', 'DELETE', 'PATCH', 'HEAD', 'OPTIONS', collation='utf8mb4_bin'),
               comment=None,
               existing_comment='请求方法',
               existing_nullable=False)
    op.alter_column('case', 'REQUEST_HEADERS',
               existing_type=mysql.JSON(),
               comment=None,
               existing_comment='请求头',
               existing_nullable=True)
    op.alter_column('case', 'REQUEST_BODY',
               existing_type=mysql.JSON(),
               comment=None,
               existing_comment='请求体',
               existing_nullable=True)
    op.alter_column('case', 'LEVEL',
               existing_type=mysql.VARCHAR(collation='utf8mb4_bin', length=1),
               comment=None,
               existing_comment='用例等级',
               existing_nullable=False)
    op.alter_column('case', 'DESCRIPTION',
               existing_type=mysql.VARCHAR(collation='utf8mb4_bin', length=32),
               comment=None,
               existing_comment='用例描述',
               existing_nullable=False)
    # ### end Alembic commands ###


def upgrade_extra():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_extra():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

