# Generated by Selenium IDE
import os
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestUpload():
    def setup_method(self, method):
        prefs = {}
        prefs["credentials_enable_service"] = False
        prefs["profile.password_manager_enabled"] = False
        option = webdriver.ChromeOptions()
        option.add_experimental_option(
            'excludeSwitches', ['enable-automation'])
        option.add_experimental_option("prefs", prefs)
        path = "E:\\chromeDriver\\{version}\\chromedriver.exe".format(
            version="85.0.4183.83")
        self.driver = webdriver.Chrome(options=option, executable_path=path)
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_23(self):
        self.driver.get("http://sit.boss-admin.zczy.com/login.html")
        self.driver.set_window_size(1936, 1056)
        self.driver.find_element(
            By.CSS_SELECTOR, ".form-group:nth-child(2) > .form-control").click()
        self.driver.find_element(
            By.CSS_SELECTOR, ".form-group:nth-child(2) > .form-control").send_keys("mabeijing56")
        self.driver.find_element(
            By.CSS_SELECTOR, ".form-group:nth-child(3) > .form-control").send_keys("mabeijing56")
        self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
        time.sleep(3)
        self.driver.find_element(By.CSS_SELECTOR, ".el-input__inner").click()
        self.driver.find_element(
            By.CSS_SELECTOR, ".el-input__inner").send_keys("结算调整")
        self.driver.find_element(
            By.CSS_SELECTOR, ".el-button--mini > span").click()
        self.driver.find_element(
            By.CSS_SELECTOR, ".el-menu-vertical-demo > .el-submenu:nth-child(1) > .el-submenu__title > span").click()
        time.sleep(1)
        self.driver.find_element(
            By.CSS_SELECTOR, ".el-menu--inline > .el-submenu:nth-child(1) > .el-submenu__title > span").click()
        time.sleep(1)
        self.driver.find_element(
            By.CSS_SELECTOR, ".is-opened > .el-menu > .el-menu-item:nth-child(1) > span").click()
        self.driver.switch_to.frame(1)
        self.driver.find_element(
            By.CSS_SELECTOR, ".easyui-linkbutton:nth-child(5) .l-btn-text").click()
        time.sleep(1)
        self.driver.find_element(By.ID, "fileImport")
        time.sleep(2)
        print('hello')
        js_click = "document.getElementById('fileImport').click()"
        self.driver.execute_script(js_click)
        # self.driver.find_element_by_xpath("//form[@id='importFileForm']/table/tbody/tr[1]/td[3]/input").send_keys(Keys.ENTER)
        time.sleep(2)
        os.system("d:\\upload.exe")
